authantic/urls.py
from django.urls import path
from authantic.views import phone_handel,signin_handle,login_handel,logout_handel

app_name="auth"

urlpatterns = [
    path("phone/",phone_handel,name="phone"),
    path("signin/",signin_handle,name="signin"),
    path("login/",login_handel,name="login"),
    path("logout/",logout_handel,name="logout"),
]

freefire/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path("giveaway/",include("giveaway.urls"),name="giveaway"),
    path("",include("home.urls"),name="home"),
    path("auth/",include("authantic.urls"),name="auth"),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

giveaway/urls.py
from django.urls import path
from giveaway.views import show_giveaway

app_name="giveaway"

urlpatterns = [
    path("show",show_giveaway,name="giveaway")
]

home/urls.py
from django.urls import path
from home.views import render_home,render_contact

app_name="home"

urlpatterns = [
    path("",render_home,name="home"),
    path("contact/",render_contact,name="contact")
]

authantic/models.py
from django.db import models
from django.contrib.auth.models import User
from authantic.helper import get_random_slug


# Create your models here.
class Profile(models.Model):
    first_name= models.CharField(max_length=30,blank=True)
    last_name= models.CharField(max_length=30,blank=True)
    User_model = models.OneToOneField(User,on_delete=models.CASCADE)
    birthday = models.DateField(default="2020-12-12")
    bio = models.TextField(max_length=250,blank=True)
    avatar = models.ImageField(upload_to="profilePic/",default = "avatar.jpg")
    slug = models.CharField(max_length=50,unique=True,blank=True)
    created = models.DateField(auto_now=True)
    update = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.User_model.username} {self.last_name}"


    def save(self, *args, **kwargs):
        self.slug = get_random_slug(self.User_model.username)
        super(Profile, self).save(*args, **kwargs)

class Phone(models.Model):
    phone_number= models.CharField(max_length=12)

    def __str__(self):
        return f"{self.phone_number}"

class PhoneUserRelationship(models.Model):
    phone = models.ForeignKey(Phone,on_delete=models.CASCADE)
    User = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.phone} -> {self.User} "

giveaway/models.py
from distutils.command.upload import upload
from django.db import models

# Create your models here.
class Giveaway(models.Model):
    title = models.CharField(max_length=20)
    desc = models.TextField(max_length=540)
    image = models.ImageField(upload_to="giveaway_image")
    created = models.DateField(auto_now=True)
    update = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"

home/models.py
from django.db import models

# Create your models here.
class Video(models.Model):
    url = models.TextField(max_length=350,unique=True)


class Contact(models.Model):
    email = models.CharField(max_length=250)
    subject = models.CharField(max_length=250)
    message = models.TextField(max_length=540)

    def __str__(self):
        return f"{self.email} send a message"

authantic/views.py
from django.shortcuts import redirect, render,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login,logout,authenticate
from urllib3 import HTTPResponse
from authantic.models import Phone,PhoneUserRelationship
from django.contrib import messages
# Create your views here.

def phone_handel(request):
    if request.method == "POST":
        phone_number = request.POST["phone"]

        if phone_number.__len__() != 12:
            return redirect("auth:phone")

        
        print(Phone.objects.filter(phone_number=phone_number).exists())
        if Phone.objects.filter(phone_number=phone_number).exists() == True :
        
            print("ok")
            return redirect("auth:phone")
        else:
               
            Phone.objects.create(phone_number=phone_number)
            context = {
                    "phone":phone_number
                }
            return render(request,"authantic/signin.html",context)
    print("ok!!!")
    return render(request,"authantic/phone.html")



def signin_handle(request):
    if request.method=="POST":
        username = request.POST["username"]
        password = request.POST["password"]
        conf_password = request.POST["conf-password"]
        phone = request.POST["phones"]
        print(phone)
        if password != conf_password:
            return redirect("auth:phone")

        if User.objects.filter(username=username).exists() == True:
            return redirect("auth:phone")

        User_module = User.objects.create_user(username=username,password=password)

        phone_obj = Phone.objects.get(phone_number=phone)
        PhoneUserRelationship.objects.create(phone=phone_obj,User=User_module)
        return redirect("auth:login")

    return redirect("auth:phone") 

def login_handel(request):
    if request.method == "POST":
        username= request.POST["username"]
        password = request.POST["password"]

        user = authenticate(username=username,password=password)
        login(request,user)
        return redirect("home:home")
    return render(request,"authantic/login.html")





@login_required
def logout_handel(request):
    print("ok")
    logout(request)
    return redirect("auth:login")

giveaway/views.py
from django.shortcuts import render
from home.models import Video
from giveaway.models import Giveaway


# Create your views here.
def show_giveaway(request):
    login_is = False
    is_give = True
    user = request.user
    if user.username != "":
        login_is = True

    Giveaways = Giveaway.objects.all()
    if Giveaways.__len__() == 0:
        is_give = False
    context = {
        "login_is":login_is,
        "user":user,
        "Giveaway":Giveaways,
        "is_give":is_give
    }
    return render(request,"giveaway/show_give_away.html",context)

home/views.py
from django.shortcuts import render
from home.models import Video,Contact


# Create your views here.
def render_home(request):
    login_is = False
    user = request.user
    print(user)
    print(type(user))
    if user.username != "":
        login_is = True
    video  = Video.objects.all()
    context = {
        "video":video,
        "login_is":login_is,
        "user":user
    }
    return render(request,"home/home.html",context)



def render_contact(request):
    login_is = False
    if request.method == "POST":
        email = request.POST["email"]
        subject = request.POST["subject"]
        message = request.POST["message"]

        context_obj = Contact.objects.create(email=email,subject=subject,message=message)
        context_obj.save()

    user = request.user
    if user.username != "":
        login_is = True
    context = {
        "login_is":login_is,
        "user":user
    }
    return render(request,"home/contact.html",context)

authantic/templates/authantic/login.html
{% extends 'form-base.html' %}

{% block heading %}Login please{% endblock heading %}

{% block actionurl %}{% endblock actionurl %}

{% block inputfileds %}

    <form action="{% url 'auth:login' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
        </div>
        <button class="btn btn-primary">submit</button>
    </form>

    <a href="{% url 'home:home' %}" style="margin-top:1rem;">skip login ->></a> <br>
    <a href="{% url 'auth:signin' %}" style="margin-top:1rem;">Create a account ->></a>
{% endblock inputfileds %}

authantic/templates/authantic/phone.html
{% extends 'form-base.html' %}

{% block heading %}Enter your phone number {% endblock heading %}

{% block actionurl %}{% url 'auth:phone' %}{% endblock actionurl %}

{% block csrf_token %}{% csrf_token %}{% endblock csrf_token %}


{% block inputIdFor %}phone{% endblock inputIdFor %}
{% block inputId %}phone{% endblock inputId %}

{% block label %}Phone number{% endblock label %}

{% block inputType %}number{% endblock inputType %}
{% block name %}phone{% endblock name %}


{% block moreinput %}
<br>
<a href="{% url 'auth:login' %}" style="margin-top:1rem;">Already has a account ->></a>

{% endblock moreinput %}

authantic/templates/authantic/signin.html
{% extends 'form-base.html' %}

{% block heading %}Signin please{% endblock heading %}




{% block actionurl %}{% url 'auth:signin' %}{% endblock actionurl %}

{% block inputfileds %}

    <form>
        {%csrf_token%}
        <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username">
        </div>
        <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
        </div>


        <div class="mb-3">
            <label for="conf-password" class="form-label">Conform password</label>
            <input type="password" class="form-control" id="conf-password" name="conf-password">
        </div>
        <input type="hidden" value={{phone}} name="phones" >
        <button class="btn btn-primary" type="submit">submit</button>

    </form>
    <a href="{% url 'auth:login' %}" style="margin-top:1rem;">already has a account ->></a>
    
{% endblock inputfileds %}

giveaway/templates/giveaway/show_give_away.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

{% include 'navbar.html' %}


<div class="container" style="display: flex;flex-wrap: wrap;align-items: flex-start;justify-content: space-around;">

    {% if is_give %}
    
    

    {% for giveaway in Giveaway %}

    <div class="card mt-5" style="max-width: 20rem;max-height: auto;">
        <img class="card-img-top" src="{{giveaway.image.url}}" alt="Error:404">
        <div class="card-body">
            <h4 class="card-title text-center">{{giveaway.title}}</h4>
            <p class="card-text text-center">{{giveaway.desc}}</p>

            <p class="text-muted">Upload at {{giveaway.created}} and last update {{giveaway.update}}</p>
        </div>
    </div>

    {% endfor %}
    {% else %}

    No giveaway is avaiable
    {% endif %}

</div>

{% endblock body %}

home/templates/home/contact.html
{% extends 'base.html' %}

{% block body %}
{% include 'navbar.html' %}

<form class="container mt-5" action="{% url 'home:contact' %}" method="POST">
    {%csrf_token%}
    <h3 class="text-center">Thanks! to contact us.</h3>
    <div class="mb-3">
        <label for="email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    
    <div class="mb-3">
        <label for="subject" class="form-label">Subject</label>
        <input type="text" class="form-control" name="subject" name="subject" id="subject">
    </div>

    <div class="mb-3">
        <label for="message" class="form-label">Example textarea</label>
        <textarea class="form-control" id="message" name="message" rows="3" placeholder="Enter your message"></textarea>
    </div>

    <button class="btn btn-primary text-center" type="submit">Send</button>
</form>

{% endblock body %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Home
{% endblock title %}



{% block body %}

{% comment %} include navbar  {% endcomment %}
{% include 'navbar.html' %}

{% comment %} include carousel  {% endcomment %}

{% include 'carousel.html' %}




{% comment %} about us  {% endcomment %}

<div class="container text-center mb-5" style="margin-top:3rem;">
    <h1>About us</h1>
    <h3>Welcome to slappy 2.0</h3>

    <p>Hello! I am slappy and this is my youtube channel for free fire game play 
        and i hope you must like it Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla qui ad, tempore ea numquam rem commodi molestiae iure quis placeat veniam voluptas fugiat nihil. Iste tempore dicta totam numquam nam in adipisci veritatis culpa! Suscipit laborum possimus, est obcaecati consequatur temporibus aut sequi optio nobis at blanditiis omnis non qui quisquam nisi fugiat nam fuga ullam numquam a veritatis, cumque soluta quam. Aliquid perspiciatis minus aliquam eum? Et magnam adipisci quas, rem, voluptatum facere repellendus blanditiis distinctio corporis dolorum culpa officia error minima fugiat sed molestias ipsam quia. Ipsam, labore ad eaque facilis ducimus qui consequatur aspernatur et illo sapiente? 
    </p>

</div>

<div class="container text-center">
    <h1 class="mb-3">Please also check my youtube channel</h1>

    <img src="{% static 'logo.jpg' %}" alt="Error:404" class="mb-3">
    <br>
    <a class="btn btn-danger" target="_blank" href="https://www.youtube.com/channel/UCs6ACOgFcRqZZ5DZl9VCPxQ">Subscribed</a>
</div>


<h3 class="m-5 text-center">All my video is here</h3>

{% comment %} render all videos  {% endcomment %}


<div class="container d-flex flex-wrap flex-row  justify-content-around overflow-auto" style="height:75vh;">

{% for video in  video%}
    
    <iframe width="400" height="250" 
    style="margin-top:2rem;"
    src="{{video.url}}"
    title="YouTube video player"
    frameborder="0"
    allow="accelerometer;autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen></iframe>

{% endfor %}

</div>





<div class="container-fluid bg-dark text-center mb-0 mt-5">
    <p class="text-light">&copy; 2022-2023</p>
</div>


{% endblock body %}

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{% static 'logo.jpg' %}" type="image/x-icon">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block css %}{% endblock css %}
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% block body %}{% endblock body %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    {% block js %}{% endblock js %}
  </body>
</html>

templates/carousel.html
<!--For carousel-->

{% load static %}
<div id="main-carousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#main-carousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#main-carousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#main-carousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static '1.jpeg' %}" class="d-block w-100 h-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static '2.jpeg' %}" class="d-block w-100 h-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="{% static '3.jpeg' %}" class="d-block w-100 h-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#main-carousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#main-carousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
</div>

templates/form-base.html
{% extends 'base.html' %}



{% block css %}
<style>

.box-container{
    height: 100vh !important;
}

</style>

{% endblock css %}





{% block body %}
    {% include 'title-nav.html' %}

    <div class="container box-container h-auto  d-flex flex-column justify-content-evenly align-items-center">
        
        <h1 class="text-muted text-uppercase">{% block heading %}{% endblock heading %}</h1>

        
        <div class="container h-75 w-75 form-box">
            <form action="{% block actionurl %}{% endblock actionurl %}"  method="POST">
    
                {% block csrf_token %}{% endblock csrf_token %}
                {% block inputfileds %}

                <div class="mb-3">
                <label for="{% block inputIdFor %}{% endblock inputIdFor %}" class="form-label">{% block label %}{% endblock label %}</label>
                <input type="{% block inputType %}{% endblock inputType %}" class="form-control" name="{% block name %}{% endblock name %}" id="{% block inputId %}{% endblock inputId %}">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                {% endblock inputfileds %}

                {% block moreinput %}{% endblock moreinput %}

            </form>
        </div>


    </div>
{% endblock body %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% load static %}
    <div class="container-fluid">
      <img src="{% static 'logo.jpg' %}" style="height:3rem;" alt="error:404">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:contact' %}">contact us</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'giveaway:giveaway' %}">Giveawaya</a>
          </li>
        </ul>
        {% if login_is %}
        <p class="text-light mt-3">Hello! {{user.username}}</p>
        <a href="{% url 'auth:logout' %}" class="btn btn-success ms-4">Logout</a>
        {% else %}
        
        <a href="{% url 'auth:login' %}" class="btn btn-success me-4">Login</a>
        <a href="{% url 'auth:signin' %}" class="btn btn-success">Signin</a>
        {% endif %}
      </div>
    </div>
</nav>

templates/title-nav.html
<nav class="navbar navbar-primary bg-primary">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">Navbar</span>
    </div>
  </nav>